openapi: 3.0.4
info:
  title: PortSnap API
  description: API documentation for PortSnap Yahoo Finance API
  version: "1.0.0"

tags:
  - name: Admin
    description: Admin-only endpoints
  - name: API
    description: Public API for clients
  - name: Auth
    description: Authentication endpoints

servers:
  - url: https://44c550b7-54f4-4174-bd1d-c51ff1e4f8c8-00-1wilq50r88xfl.janeway.replit.dev/
    description: Dev Server API
  - url: https://api-portsanp.up.railway.app/
    description: Server Railway API
paths:
  /admin/info:
    $ref: 'paths/admin.yaml#/paths/info'
  /admin/info/refresh:
    $ref: 'paths/admin.yaml#/paths/info_refresh'
  /admin/users:
    $ref: 'paths/admin.yaml#/paths/users'
  /admin/users/{id}:
    $ref: 'paths/admin.yaml#/paths/users_id'
  /admin/memberships/{userId}:
    $ref: 'paths/admin.yaml#/paths/memberships_userId'
  /admin/tokens:
    $ref: 'paths/admin.yaml#/paths/tokens'
    /admin/tokens/{id}:
      $ref: 'paths/admin.yaml#/paths/tokens_id'
  /admin/logs:
    $ref: 'paths/admin.yaml#/paths/logs'
    /admin/autocomplete:
      $ref: 'paths/admin.yaml#/paths/autocomplete'
  /auth/login:
    $ref: './paths/auth.yaml#/paths/login'
  /auth/logout:
    $ref: './paths/auth.yaml#/paths/logout'
  #$ref: 'paths/admin.yaml#/paths'

components:
  schemas:
    $ref: 'components/schemas.yaml#/components/schemas'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    cookieAuth:
      type: apiKey
      in: header
      name: x-access-token
security:
- cookieAuth: []

