openapi: 3.0.4
info:
  title: PortSnap API
  description: API documentation for PortSnap Yahoo Finance API
  version: "1.0.0"

tags:
  - name: Admin
    description: Admin-only endpoints
  - name: Admin - Payment
    description: Admin-only endpoints for payment management
  - name: User - Payment
    description: User endpoints for payment management
  - name: API
    description: Public API for clients
  - name: Auth
    description: Authentication endpoints

servers:
  - url: https://44c550b7-54f4-4174-bd1d-c51ff1e4f8c8-00-1wilq50r88xfl.janeway.replit.dev/
    description: Dev Server API
  - url: https://api-portsanp.up.railway.app/
    description: Server Railway API
paths:
  /admin/info:
    $ref: 'paths/admin.yaml#/paths/info'
  /admin/info/refresh:
    $ref: 'paths/admin.yaml#/paths/info_refresh'
  /admin/users:
    $ref: 'paths/admin.yaml#/paths/users'
  /admin/users/{id}:
    $ref: 'paths/admin.yaml#/paths/users_id'
  /admin/memberships/{userId}:
    $ref: 'paths/admin.yaml#/paths/memberships_userId'
  /admin/tokens:
    $ref: 'paths/admin.yaml#/paths/tokens'
    /admin/tokens/{id}:
      $ref: 'paths/admin.yaml#/paths/tokens_id'
  /admin/logs:
    $ref: 'paths/admin.yaml#/paths/logs'
  /admin/autocomplete:
    $ref: 'paths/admin.yaml#/paths/autocomplete'
  /admin/payments:
    $ref: 'paths/admin.yaml#/paths/payments'
  /admin/refunds:
    $ref: 'paths/admin.yaml#/paths/refunds'
  /admin/payments/{id}:
    $ref: 'paths/admin.yaml#/paths/payments_id'
  /admin/statistics:
    $ref: 'paths/admin.yaml#/paths/statistics'
  /admin/refund/{id}/approve:
    $ref: 'paths/admin.yaml#/paths/refund_id_approve'
  /admin/refund/{id}/reject:
    $ref: 'paths/admin.yaml#/paths/refund_id_reject'
  /auth/payments/history:
    $ref: 'paths/users.yaml#/paths/payments_history'
  /auth/payments/{id}/refund-request:
    $ref: 'paths/users.yaml#/paths/payments_id_refund-request'
  /auth/payments:
    $ref: 'paths/users.yaml#/paths/payments'
  /auth/login:
    $ref: './paths/auth.yaml#/paths/login'
  /auth/logout:
    $ref: './paths/auth.yaml#/paths/logout'
  #$ref: 'paths/admin.yaml#/paths'

components:
  schemas:
    $ref: 'components/schemas.yaml#/components/schemas'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    cookieAuth:
      type: apiKey
      in: header
      name: x-access-token
security:
- cookieAuth: []

